//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdderApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OrderBaseEntities : DbContext
    {
        private static OrderBaseEntities _context;

        public OrderBaseEntities()
            : base("name=OrderBaseEntities")
        {
        }
        public static OrderBaseEntities GetContext()
        {
            if (_context == null)
                _context = new OrderBaseEntities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<price> prices { get; set; }
        public virtual DbSet<pricePC> pricePCs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
    }
}
