//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdderApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int id { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string FioCustomer { get; set; }
        public string priceCode { get; set; }
        public string Note { get; set; }
        public decimal SummPrice { get; set; }
        public string pricePCCode { get; set; }
    
        public virtual price price { get; set; }
        public virtual pricePC pricePC { get; set; }
    }
}
